# Site settings
title: XFTTYY | My Blog
description: "一个技术博客"
url: "http2://e7868a.github.io"
author:
  name: "Yang Jian"
  email: "marine8086@hotmail.com"
  url: "https://e7868a.github.io"

# Build settings
baseurl: /
markdown: kramdown
highlighter: rouge
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
    input: GFM
    syntax_highlighter_opts:
        default_lang: html

plugins: [jekyll-paginate]

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
